---
- name: Configuring ElasticSearch
  hosts: deploy
  user: azureuser 
  become_method: sudo
  become: yes
  gather_facts: false
 
  tasks:
  - name: install java 11
    apt: 
      name: openjdk-11-jdk
      purge: yes
      state: present
  - name: Set Java home
    shell: sudo echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> /etc/environment
  - name: export Java home
    shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 
  - name: Download ElasticSearch package
    shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - name: check package list
    shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  - name: update cache and ignore errors in case of problems
    apt: update_cache=yes
    ignore_errors: yes
  - name: install elasticsearch
    apt: 
      name: elasticsearch
      purge: yes
      state: present
    notify: restart elasticsearch
  handlers:
  - name: restart elasticsearch
    action: service name=elasticsearch state=restarted
